apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jygb1u4cs-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jygb1u4cs-java-quarkus 
  name: jygb1u4cs-java-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jygb1u4cs-java-quarkus 
